// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awpkwcbkmakikqwtiack.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3cGt3Y2JrbWFraWtxd3RpYWNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MTkyMTksImV4cCI6MjA3Mjk5NTIxOX0.13a3IIGKEPhMK0m6Sn-kz12eyvLJzzs4AGt9aUmem3M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});